#pragma once
#include "../vendor/scripthookv/inc/main.h"
#include "../vendor/scripthookv/inc/natives.h"
#include "../vendor/minhook/include/MinHook.h"
#include "nativesNoNamespaces.h"
#include "Random.h"
#include "DebugMenu.h"
#include <Windows.h>
#include <WinUser.h>
#include <Psapi.h>
#include <fstream>
#include <array>
#include <string>
#include <sstream>
#include <stdexcept>
#include <memory>