namespace ConfigApp
{
    public static class Effects
    {
        public struct EffectInfo
        {
            public string? Name { get; set; }
            public string? Description { get; set; }
            public EffectCategory EffectCategory { get; set; }
            public bool IsTimed { get; set; }
            public bool IsShort { get; set; }

            public EffectInfo(string name, string description, EffectCategory effectCategory = EffectCategory.Unknown, bool isTimed = false, bool isShort = false)
            {
                Name = name;
                Description = description;
                EffectCategory = effectCategory;
                IsTimed = isTimed;
                IsShort = isShort;
            }
        }

        public enum EffectCategory
        {
            Unknown = -1,
            Player,
            Vehicle,
            Peds,
            Screen,
            Time,
            Weather,
            Misc,
            Meta
        }

        public enum EffectTimedType
        {
            Permanent = -3,
            Custom, // Not used here, CustomTime is set to something other than 0 instead
            NotTimed,
            Normal,
            Short,
        }

        public static readonly Dictionary<string, EffectInfo> EffectsMap = new()
        {
            // Meta
            { "meta_spawn_multiple_effects", new EffectInfo("Combo Time", "Spawns two additional effects simultaneously.", EffectCategory.Meta, true) },
            { "meta_effect_duration_0_5x", new EffectInfo("0.5x Effect Duration", "Reduces the duration of all active timed effects to half.", EffectCategory.Meta, true) },
            { "meta_effect_duration_2x", new EffectInfo("2x Effect Duration", "Doubles the duration of all active timed effects.", EffectCategory.Meta, true) },
            { "meta_hide_chaos_ui", new EffectInfo("What's Happening??", "Hides the chaos mod UI from the screen.", EffectCategory.Meta, true) },
            { "meta_nochaos", new EffectInfo("No Chaos", "Disables chaos and clears all currently active effects.", EffectCategory.Meta, true) },
            { "meta_re_invoke", new EffectInfo("Re-Invoke Previous Effects", "Re-invokes the 5 most recently triggered effects.", EffectCategory.Meta) },
            { "meta_timerspeed_0_5x", new EffectInfo("0.5x Timer Speed", "Slows the chaos effect dispatch timer to half speed.", EffectCategory.Meta, true) },
            { "meta_timerspeed_2x", new EffectInfo("2x Timer Speed", "Speeds up the chaos effect dispatch timer to double speed.", EffectCategory.Meta, true) },
            { "meta_timerspeed_5x", new EffectInfo("5x Timer Speed", "Speeds up the chaos effect dispatch timer to 5x speed.", EffectCategory.Meta, true, true) },
            { "meta_votingmode_majority", new EffectInfo("Majority Voting", "Switches Twitch voting to majority-wins mode.", EffectCategory.Meta, true) },
            { "meta_votingmode_antimajority", new EffectInfo("Minority Voting", "Switches Twitch voting to minority-wins mode.", EffectCategory.Meta, true) },
            
            // Screen / Timecycle
            { "player_binoculars", new EffectInfo("Binoculars", "Applies a zoomed binoculars-style camera.", EffectCategory.Screen, true) },
            { "screen_bouncyradar", new EffectInfo("Bouncy Radar", "Makes the radar minimap bounce around the screen like a DVD screensaver.", EffectCategory.Screen, true) },
            { "misc_dvdscreensaver", new EffectInfo("DVD Screensaver", "Displays a bouncing DVD logo across the screen.", EffectCategory.Screen, true, true) },
            { "player_flip_camera", new EffectInfo("Turn Turtle", "Flips the camera view upside-down.", EffectCategory.Screen, true, true) },
            { "misc_flip_ui", new EffectInfo("Flipped HUD", "Flips all HUD elements to the opposite side of the screen.", EffectCategory.Screen, true) },
            { "player_heatvision", new EffectInfo("Heat Vision", "Enables a heat-vision overlay.", EffectCategory.Screen, true, true) },
            { "screen_maximap", new EffectInfo("Maximap", "Enlarges the radar into a giant map covering most of the screen.", EffectCategory.Misc, true) },
            { "player_nightvision", new EffectInfo("Night Vision", "Enables a night-vision overlay.", EffectCategory.Screen, true) },
            { "no_hud", new EffectInfo("No HUD", "Hides all HUD elements including the radar and disables the pause map.", EffectCategory.Screen, true) },
            { "no_radar", new EffectInfo("No Radar", "Hides the radar while keeping other HUD elements visible.", EffectCategory.Screen, true) },
            { "player_on_demand_cartoon", new EffectInfo("On-Demand TV", "Shows a random TV broadcast in the middle of the screen.", EffectCategory.Screen, true) },
            { "player_quake_fov", new EffectInfo("Quake FOV", "Sets a very wide field of view similar to Quake.", EffectCategory.Screen, true) },
            { "screen_realfp", new EffectInfo("Real First Person", "Attaches the camera to the player's head bone for true first-person view.", EffectCategory.Screen, true) },
            { "player_sick_cam", new EffectInfo("I Feel Sick", "Makes the camera wobble and zoom erratically to simulate nausea.", EffectCategory.Screen, true, true) },
            { "player_spin_camera", new EffectInfo("Spinning Camera", "Continuously rotates the camera around the player.", EffectCategory.Screen, true, true) },
            { "screen_mexico", new EffectInfo("Is This What Mexico Looks Like?", "Applies a hazy green timecycle modifier making everything look like Mexico.", EffectCategory.Screen, true) },
            { "screen_bright", new EffectInfo("Deep Fried", "Applies extreme overexposure and enhanced weather effects.", EffectCategory.Screen, true, true) },
            { "screen_fog", new EffectInfo("Extreme Fog", "Applies extreme fog that severely reduces visibility.", EffectCategory.Screen, true, true) },
            { "screen_lowrenderdist", new EffectInfo("Where Did Everything Go?", "Reduces the rendering distance so distant objects disappear.", EffectCategory.Screen, true, true) },
            { "screen_lsd", new EffectInfo("LSD", "Applies psychedelic visual distortions and drunk driving mechanics.", EffectCategory.Screen, true) },
            { "screen_fullbright", new EffectInfo("Fullbright", "Illuminates the entire world at maximum brightness via timecycle.", EffectCategory.Screen, true) },
            { "screen_bubblevision", new EffectInfo("Bubble Vision", "Applies a bubble-like visual distortion with audio warping.", EffectCategory.Screen, true, true) },
            { "screen_lsnoire", new EffectInfo("LS Noire", "Applies a black-and-white film noir timecycle and dresses the player in a suit.", EffectCategory.Screen, true) },
            { "screen_needglasses", new EffectInfo("I Need Glasses", "Blurs the screen to simulate very poor eyesight.", EffectCategory.Screen, true, true) },
            { "timecycle_fuzzy", new EffectInfo("Static", "Overlays a broken-TV static effect on the screen.", EffectCategory.Screen, true, true) },
            { "timecycle_darkworld", new EffectInfo("A Dark World", "Makes the world pitch-dark using a vault timecycle.", EffectCategory.Screen, true, true) },
            { "screen_arc", new EffectInfo("Arced Screen", "Warps the screen in a curved arc using a post-process shader.", EffectCategory.Screen, true, true) },
            { "screen_colorfulworld", new EffectInfo("Colorful World", "Replaces textures with animated colourful patterns via shader.", EffectCategory.Screen, true) },
            { "screen_dimwarp", new EffectInfo("Dimension Warp", "Distorts screen-space texture coordinates with a dimensional warp shader.", EffectCategory.Screen, true, true) },
            { "screen_fckautorotate", new EffectInfo("Goddamn Auto-Rotate", "Rotates screen coordinates to simulate an auto-rotate gone wrong.", EffectCategory.Screen, true, true) },
            { "screen_foldedscreen", new EffectInfo("Folded Screen", "Folds the screen in half using a shader effect.", EffectCategory.Screen, true) },
            { "screen_fourthdimension", new EffectInfo("Fourth Dimension", "Samples displaced texels using the red channel, creating dimensional distortion.", EffectCategory.Screen, true, true) },
            { "screen_hueshift", new EffectInfo("Hue Shift", "Applies a random hue rotation to all screen colours via shader.", EffectCategory.Screen, true) },
            { "screen_invertedcolors", new EffectInfo("Inverted Colors", "Inverts all colours on the screen.", EffectCategory.Screen, true) },
            { "screen_localcoop", new EffectInfo("Split Screen Co-op", "Tiles the screen output 5x to simulate split-screen co-op via shader.", EffectCategory.Screen, true, true) },
            { "screen_mirrored", new EffectInfo("Mirrored Screen", "Mirrors the screen horizontally via shader.", EffectCategory.Screen, true) },
            { "screen_rgbland", new EffectInfo("RGB Land", "Replaces textures with animated RGB colour bars via shader.", EffectCategory.Screen, true) },
            { "screen_screenfreakout", new EffectInfo("Screen Freakout", "Applies time-based sinusoidal distortion to texture coordinates.", EffectCategory.Screen, true, true) },
            { "screen_screenpotato", new EffectInfo("Potato", "Pixelates the screen by quantising texture coordinates.", EffectCategory.Screen, true, true) },
            { "screen_shatteredscreen", new EffectInfo("Shattered Screen", "Makes the screen appear shattered using modulo texture-coordinate manipulation.", EffectCategory.Screen, true) },
            { "screen_swappedcolors", new EffectInfo("Swapped Colors", "Randomly swaps two of the three RGB colour channels.", EffectCategory.Screen, true) },
            { "screen_textureless", new EffectInfo("Textureless", "Renders everything as flat white, removing all textures.", EffectCategory.Screen, true) },
            { "screen_tnpanel", new EffectInfo("TN Panel", "Simulates a TN-panel LCD colour shift at extreme viewing angles.", EffectCategory.Screen, true) },
            { "screen_warpedcam", new EffectInfo("Warped Camera", "Warps the screen with a sinusoidal distortion shader.", EffectCategory.Screen, true, true) },
            
            // Time / Weather
            { "time_morning", new EffectInfo("Set Time To Morning", "Sets the in-game time to 8:00 AM.", EffectCategory.Time) },
            { "time_day", new EffectInfo("Set Time To Daytime", "Sets the in-game time to 12:00 PM.", EffectCategory.Time) },
            { "time_evening", new EffectInfo("Set Time To Evening", "Sets the in-game time to 6:00 PM.", EffectCategory.Time) },
            { "time_night", new EffectInfo("Set Time To Night", "Sets the in-game time to midnight.", EffectCategory.Time) },
            { "time_quickday", new EffectInfo("Timelapse", "Advances the in-game clock rapidly to create a timelapse effect.", EffectCategory.Time, true) },
            { "time_local_time", new EffectInfo("Set Time To System Time", "Sets the in-game time and date to match the system clock.", EffectCategory.Time) },
            { "time_x02", new EffectInfo("x0.2 Gamespeed", "Slows game speed to 0.2x and lowers audio pitch accordingly.", EffectCategory.Time, true, true) },
            { "time_x05", new EffectInfo("x0.5 Gamespeed", "Slows game speed to 0.5x and lowers audio pitch accordingly.", EffectCategory.Time, true, true) },
            { "time_superhot", new EffectInfo("Superhot", "Game speed scales dynamically from 0.2x to 1x based on the player's movement speed.", EffectCategory.Time, true) },
            { "time_lag", new EffectInfo("Lag", "Simulates network lag by periodically snapping vehicles and peds backwards.", EffectCategory.Misc, true, true) },
            { "weather_extrasunny", new EffectInfo("Extra Sunny Weather", "Sets the weather to extra sunny.", EffectCategory.Weather) },
            { "weather_stormy", new EffectInfo("Stormy Weather", "Sets the weather to a heavy thunderstorm.", EffectCategory.Weather) },
            { "weather_foggy", new EffectInfo("Foggy Weather", "Sets the weather to thick fog.", EffectCategory.Weather) },
            { "weather_neutral", new EffectInfo("Neutral Weather", "Sets the weather to neutral overcast.", EffectCategory.Weather) },
            { "weather_snowy", new EffectInfo("Snowy Weather", "Sets the weather to snowfall.", EffectCategory.Weather) },
            { "weather_randomizer", new EffectInfo("Disco Weather", "Randomly cycles through weather types every second.", EffectCategory.Weather, true) },
            { "world_snow", new EffectInfo("Snow", "Enables snow accumulation and sets the weather to snowfall.", EffectCategory.Weather, true) },
            
            // Misc
            { "misc_airstrike", new EffectInfo("Airstrike Inbound", "Calls in an airstrike that rains rockets around the player.", EffectCategory.Misc, true) },
            { "world_blackhole", new EffectInfo("Black Hole", "Spawns a growing black hole that pulls all nearby entities toward it.", EffectCategory.Misc, true, true) },
            { "world_blackout", new EffectInfo("Blackout", "Kills all streetlights and plunges the world into darkness.", EffectCategory.Misc, true) },
            { "misc_boost_velocity", new EffectInfo("Speed Boost", "Multiplies the velocity of all nearby entities by 5.", EffectCategory.Misc) },
            { "misc_clone_on_death", new EffectInfo("Resurrection Day", "Clones every ped or vehicle that dies, replacing it with a fresh copy.", EffectCategory.Misc, true, true) },
            { "cocktail_shaker", new EffectInfo("Cocktail Shaker", "Repeatedly applies alternating sideways forces to shake all nearby entities.", EffectCategory.Misc, true, true) },
            { "misc_earthquake", new EffectInfo("Earthquake", "Continuously applies random upward and downward forces to all entities.", EffectCategory.Misc, true, true) },
            { "misc_esp", new EffectInfo("ESP", "Draws ESP skeleton outlines over all nearby non-player peds.", EffectCategory.Misc, true) },
            { "misc_fakecrash", new EffectInfo("Fake Crash", "Simulates a game crash screen without actually crashing.", EffectCategory.Misc) },
            { "misc_fireworks", new EffectInfo("Fireworks!", "Continuously launches firework rockets and explosions around the player.", EffectCategory.Misc, true) },
            { "misc_flamethrower", new EffectInfo("Flamethrowers", "Replaces all gunfire with flamethrower particle effects.", EffectCategory.Misc, true) },
            { "misc_fps_limit", new EffectInfo("Console Experience", "Limits the frame rate to simulate a console performance experience.", EffectCategory.Misc, true, true) },
            { "misc_get_towed", new EffectInfo("Get Towed", "Spawns a tow truck that hooks up and tows the player's vehicle away.", EffectCategory.Misc) },
            { "misc_ghost_world", new EffectInfo("Ghost Town", "Makes all entities flicker between visible and transparent.", EffectCategory.Misc, true) },
            { "misc_go_to_jail", new EffectInfo("Bad Boys", "Teleports the player to the Bolingbroke Penitentiary.", EffectCategory.Misc) },
            { "lowgravity", new EffectInfo("Low Gravity", "Reduces world gravity to half strength.", EffectCategory.Misc, true, true) },
            { "verylowgravity", new EffectInfo("Very Low Gravity", "Reduces world gravity to a very low level.", EffectCategory.Misc, true, true) },
            { "insanegravity", new EffectInfo("Insane Gravity", "Cranks gravity to an extreme level, slamming everything to the ground.", EffectCategory.Misc, true, true) },
            { "invertgravity", new EffectInfo("Invert Gravity", "Reverses gravity so all entities fall upward.", EffectCategory.Misc, true, true) },
            { "misc_sideways_gravity", new EffectInfo("Sideways Gravity", "Applies gravity in a random horizontal direction.", EffectCategory.Misc, true, true) },
            { "misc_randomgravity", new EffectInfo("Random Gravity", "Changes the gravity direction to a new random vector every few seconds.", EffectCategory.Misc, true, true) },
            { "misc_highpitch", new EffectInfo("High Pitch", "Shifts all game audio to a very high pitch.", EffectCategory.Misc, true) },
            { "player_arenawarstheme", new EffectInfo("Play Arena Wars Theme", "Plays Arena Wars lobby music.", EffectCategory.Misc, true) },
            { "invertvelocity", new EffectInfo("Invert Current Velocity", "Reverses the velocity of all nearby entities.", EffectCategory.Misc) },
            { "misc_jumpy_props", new EffectInfo("Jumpy Props", "Makes all props bounce up and down in a sine-wave pattern.", EffectCategory.Misc, true) },
            { "misc_lowpitch", new EffectInfo("Low Pitch", "Shifts all game audio to a very low pitch.", EffectCategory.Misc, true) },
            { "world_lowpoly", new EffectInfo("Low Render Distance", "Reduces render distance to low-poly LOD levels and freezes peds in place.", EffectCategory.Misc, true) },
            { "meteorrain", new EffectInfo("Meteor Shower", "Spawns meteors that rain from the sky and explode on impact.", EffectCategory.Misc, true) },
            { "misc_midas", new EffectInfo("Midas Touch", "Turns everything the player touches gold and converts it to cash pickups.", EffectCategory.Player, true) },
            { "player_moneydrops", new EffectInfo("Money Rain", "Rains money bags around the player.", EffectCategory.Misc, true) },
            { "misc_muffled_audio", new EffectInfo("Muffled Audio", "Applies a low-pass filter to all audio, muffling high frequencies.", EffectCategory.Misc, true) },
            { "misc_news_team", new EffectInfo("News Team", "Dispatches a news helicopter with a cameraman to cover the player live.", EffectCategory.Misc, true, true) },
            { "player_nophone", new EffectInfo("No Phone", "Disables the player's phone.", EffectCategory.Misc, true) },
            { "misc_nosky", new EffectInfo("No Sky", "Removes the skybox, leaving the background pitch-black.", EffectCategory.Misc, true) },
            { "nothing", new EffectInfo("Nothing", "Does nothing, but displays a fake alarming effect name to confuse viewers.", EffectCategory.Misc) },
            { "misc_remove_water", new EffectInfo("Drought", "Drains all bodies of water from the game world.", EffectCategory.Misc, true) },
            { "misc_nowaypoint", new EffectInfo("Remove Waypoint", "Clears the current GPS waypoint.", EffectCategory.Misc) },
            { "misc_oilleaks", new EffectInfo("Oil Trails", "Leaves oil-slick decals on the ground behind moving vehicles and peds.", EffectCategory.Misc, true) },
            { "misc_onebullet", new EffectInfo("One Bullet Mags", "Limits every weapon to a single bullet per magazine.", EffectCategory.Peds, true) },
            { "misc_pause", new EffectInfo("Pause", "Pauses the game.", EffectCategory.Misc) },
            { "misc_pay_respects", new EffectInfo("Pay Respects", "Forces the player to hold F to pay respects or face an explosion.", EffectCategory.Misc, true, true) },
            { "misc_portrait", new EffectInfo("Portrait Mode", "Adds black pillarbox bars to simulate portrait-mode recording.", EffectCategory.Misc, true) },
            { "misc_quick_sprunk_stop", new EffectInfo("Quick Sprunk Stop", "Spawns an interactive Sprunk vending machine in front of the player.", EffectCategory.Misc) },
            { "peds_rainbowweps", new EffectInfo("Rainbow Weapons", "Randomly cycles all weapon tints through rainbow colours.", EffectCategory.Misc, true) },
            { "misc_rampjam", new EffectInfo("Ramp Jam", "Spawns a ramp in front of the player's vehicle when they jump.", EffectCategory.Misc, true) },
            { "misc_random_waypoint", new EffectInfo("Set Random Waypoint", "Places the GPS waypoint at a random location on the map.", EffectCategory.Misc) },
            { "misc_credits", new EffectInfo("Roll Credits", "Rolls the GTA V end credits with music and grants temporary invincibility.", EffectCategory.Misc, true, true) },
            { "misc_solid_props", new EffectInfo("Solid Props", "Makes all props indestructible and immovable.", EffectCategory.Misc, true) },
            { "misc_spawnufo", new EffectInfo("Spawn UFO", "Spawns a UFO prop at the player's location.", EffectCategory.Misc) },
            { "misc_spawnferriswheel", new EffectInfo("Spawn Ferris Wheel", "Spawns a Ferris wheel prop at the player's location.", EffectCategory.Misc) },
            { "misc_spawn_orange_ball", new EffectInfo("Spawn Orange Ball", "Spawns a large orange ball with random physics weight in front of the player.", EffectCategory.Misc) },
            { "misc_spinning_props", new EffectInfo("Spinning Props", "Makes all props spin rapidly on the spot.", EffectCategory.Misc, true) },
            { "misc_stuffguns", new EffectInfo("Improvised Weaponry", "Makes bullets physically spawn random props, peds, or vehicles on impact.", EffectCategory.Misc, true, true) },
            { "misc_superstunt", new EffectInfo("Super Stunt", "Launches the player's vehicle off a ramp at high speed.", EffectCategory.Misc) },
            { "chaosmode", new EffectInfo("Doomsday", "Triggers a thunderstorm, sends all vehicles haywire, and impairs the player's steering.", EffectCategory.Misc, true, true) },
            { "misc_uturn", new EffectInfo("U-Turn", "Rotates all nearby entities 180 degrees and reverses their velocity.", EffectCategory.Misc) },
            { "misc_fakeuturn", new EffectInfo("Fake U-Turn", "Appears to do a U-turn effect but swaps back immediately after.", EffectCategory.Misc) },
            { "misc_vehicle_rain", new EffectInfo("Vehicle Rain", "Spawns random fully-upgraded vehicles around the player every 500 ms.", EffectCategory.Misc, true, true) },
            { "misc_weirdpitch", new EffectInfo("Weird Pitch", "Rapidly randomises audio pitch every frame.", EffectCategory.Misc, true) },
            { "world_whalerain", new EffectInfo("Whale Rain", "Drops dead exploding whales from the sky.", EffectCategory.Misc, true) },
            { "misc_witness_protection", new EffectInfo("Witness Protection", "Surrounds the player with 20 identical-looking peds in a ring.", EffectCategory.Misc, true) },
            
            // Player
            { "player_suicide", new EffectInfo("Suicide", "Kills the player immediately.", EffectCategory.Player) },
            { "player_plus2stars", new EffectInfo("+2 Wanted Stars", "Increases wanted level by 2 stars.", EffectCategory.Player) },
            { "player_5stars", new EffectInfo("5 Wanted Stars", "Sets wanted level to 5 stars.", EffectCategory.Player) },
            { "player_neverwanted", new EffectInfo("Never Wanted", "Continuously zeroes the wanted level.", EffectCategory.Player, true) },
            { "player_heal", new EffectInfo("HESOYAM", "Fully heals the player and deposits $250,000 (HESOYAM cheat).", EffectCategory.Player) },
            { "player_ignite", new EffectInfo("Ignite Player", "Sets the player or their vehicle on fire.", EffectCategory.Player) },
            { "player_upupaway", new EffectInfo("Launch Player Up", "Launches the player high into the air.", EffectCategory.Player) },
            { "tp_lsairport", new EffectInfo("Teleport To LS Airport", "Teleports the player to Los Santos International Airport.", EffectCategory.Player) },
            { "tp_mazebanktower", new EffectInfo("Teleport To Top Of Maze Bank Tower", "Teleports the player to the top of Maze Bank Tower.", EffectCategory.Player) },
            { "tp_fortzancudo", new EffectInfo("Teleport To Fort Zancudo", "Teleports the player to Fort Zancudo.", EffectCategory.Player) },
            { "tp_skyfall", new EffectInfo("Teleport To Heaven", "Teleports the player thousands of metres into the sky.", EffectCategory.Player) },
            { "tp_mountchilliad", new EffectInfo("Teleport To Mount Chiliad", "Teleports the player to the peak of Mount Chiliad.", EffectCategory.Player) },
            { "tp_random", new EffectInfo("Teleport To Random Location", "Teleports the player to a random location on the map.", EffectCategory.Player) },
            { "tp_mission", new EffectInfo("Teleport To Random Mission", "Teleports the player to a random mission start marker.", EffectCategory.Player) },
            { "tp_fake", new EffectInfo("Fake Teleport", "Fakes a teleport by fading the screen but leaving the player in place.", EffectCategory.Player) },
            { "player_tp_store", new EffectInfo("Teleport to Random Store", "Teleports the player to a random convenience store.", EffectCategory.Player) },
            { "player_tpclosestveh", new EffectInfo("Set Player Into Closest Vehicle", "Puts the player into the nearest vehicle.", EffectCategory.Player) },
            { "player_tpeverything", new EffectInfo("Teleport Everything To Player", "Teleports all nearby entities to the player's position.", EffectCategory.Player) },
            { "player_tptowaypoint", new EffectInfo("Teleport To Waypoint", "Teleports the player directly to their current waypoint.", EffectCategory.Player) },
            { "player_tpfront", new EffectInfo("Teleport Player A Few Meters", "Teleports the player a short distance forward.", EffectCategory.Player) },
            { "player_nosprint", new EffectInfo("No Sprint & No Jump", "Disables sprint and jump.", EffectCategory.Player, true) },
            { "player_invincible", new EffectInfo("Invincibility", "Makes the player fully invincible for the duration.", EffectCategory.Player, true) },
            { "player_nospecial", new EffectInfo("No Special Ability", "Prevents the player from using their special ability.", EffectCategory.Player, true) },
            { "player_forcedcinematiccam", new EffectInfo("Cinematic Vehicle Cam", "Enables cinematic driving cam and disables drive-bys.", EffectCategory.Vehicle, true) },
            { "player_break", new EffectInfo("Autopilot", "Autopilot drives and fights for the player.", EffectCategory.Player, true, true) },
            { "player_noragdoll", new EffectInfo("No Ragdoll", "Disables ragdoll for all entities.", EffectCategory.Peds, true) },
            { "player_ragdoll", new EffectInfo("Ragdoll", "Forces the player into an immediate ragdoll.", EffectCategory.Player) },
            { "player_ragdollondmg", new EffectInfo("Player Ragdolls When Shot", "Makes the player ragdoll every time they take any damage.", EffectCategory.Player, true) },
            { "player_superrun", new EffectInfo("Super Run & Super Jump", "Greatly increases run speed and enables unlimited super jumps.", EffectCategory.Player, true) },
            { "player_drunk", new EffectInfo("Drunk", "Makes the player drunk with screen sway and impaired vehicle handling.", EffectCategory.Player, true) },
            { "player_ohko", new EffectInfo("One Hit KO", "One-shot kills all peds and nearly kills the player.", EffectCategory.Peds, true) },
            { "player_famous", new EffectInfo("You Are Famous", "Nearby peds become fans and follow the player.", EffectCategory.Peds, true) },
            { "player_explosivecombat", new EffectInfo("Explosive Combat", "Melee and bullet impacts cause explosions.", EffectCategory.Peds, true) },
            { "player_allweps", new EffectInfo("Give All Weapons", "Gives the player every weapon with maximum ammo.", EffectCategory.Player) },
            { "player_aimbot", new EffectInfo("Aimbot", "Auto-aims and fires at the nearest ped continuously.", EffectCategory.Player, true) },
            { "player_randclothes", new EffectInfo("Randomize Player Clothes", "Randomises the player's entire outfit.", EffectCategory.Player) },
            { "player_setintorandveh", new EffectInfo("Set Player Into Random Vehicle", "Teleports the player into a random vehicle.", EffectCategory.Player) },
            { "player_clone", new EffectInfo("Clone Player", "Spawns a friendly or hostile clone of the player.", EffectCategory.Player) },
            { "player_poof", new EffectInfo("Deadly Aim", "Instantly kills and detonates any entity the player aims at.", EffectCategory.Player, true) },
            { "poorboi", new EffectInfo("Poor Boy", "Sets the player's cash to zero.", EffectCategory.Player) },
            { "player_heavyrecoil", new EffectInfo("Heavy Recoil", "Greatly increases weapon recoil on every shot.", EffectCategory.Player, true) },
            { "player_keeprunning", new EffectInfo("Help My W Key Is Stuck", "Locks the player's movement to forward at full sprint.", EffectCategory.Player, true, true) },
            { "player_forcefield", new EffectInfo("Forcefield", "Pushes nearby peds and vehicles away from the player.", EffectCategory.Player, true, true) },
            { "player_afk", new EffectInfo("AFK", "Freezes the player's controls completely.", EffectCategory.Player, true, true) },
            { "player_bees", new EffectInfo("Bees", "Surrounds the player with a swarm of damaging bees.", EffectCategory.Player, true) },
            { "player_blimp_strats", new EffectInfo("Blimp Strats", "Launches the player into the cockpit of a blimp.", EffectCategory.Player) },
            { "player_copyforce", new EffectInfo("Use The Force", "Transfers the player's momentum to nearby entities.", EffectCategory.Player, true, true) },
            { "player_dead_eye", new EffectInfo("Dead Eye", "Slows time while aiming and kills targets with explosive shots.", EffectCategory.Player, true) },
            { "player_fling_player", new EffectInfo("Fling Player", "Flings the player into the air with a random force.", EffectCategory.Player) },
            { "player_gta_2", new EffectInfo("GTA 2", "Switches the camera to a top-down GTA 2-style isometric view.", EffectCategory.Player, true, true) },
            { "player_grav_sphere", new EffectInfo("Gravity Sphere", "Creates a gravity sphere that orbits and pulls nearby entities.", EffectCategory.Player, true, true) },
            { "player_hacking", new EffectInfo("Realistic Hacking", "Displays a hacking mini-game that kills the player on failure.", EffectCategory.Player) },
            { "player_gravity", new EffectInfo("Gravity Field", "Creates a gravity field that repels nearby entities.", EffectCategory.Player, true, true) },
            { "player_illegalinnocence", new EffectInfo("Innocence Is Illegal", "Slowly escalates the wanted level while blocking the player from evading it.", EffectCategory.Player, true) },
            { "player_jump_jump", new EffectInfo("Jump! Jump!", "Forces the player to jump repeatedly every 500 ms.", EffectCategory.Player, true, true) },
            { "player_kickflip", new EffectInfo("Kickflip", "Applies a rotational flip force to the player or vehicle.", EffectCategory.Player) },
            { "player_laggy_camera", new EffectInfo("Delayed Camera", "Introduces heavy lag to the camera movement.", EffectCategory.Player, true) },
            { "player_lockcamera", new EffectInfo("Lock Camera", "Locks the camera in its current direction.", EffectCategory.Player, true) },
            { "player_movementx5", new EffectInfo("5x Movement Speed", "Increases the player's movement speed by 5x.", EffectCategory.Player, true) },
            { "player_movementx10", new EffectInfo("10x Movement Speed", "Increases the player's movement speed by 10x.", EffectCategory.Player, true) },
            { "player_movementx05", new EffectInfo("0.5x Movement Speed", "Reduces the player's movement speed to 0.5x.", EffectCategory.Player, true, true) },
            { "player_no_random_movement", new EffectInfo("Disable Random Direction", "Randomly disables one movement direction at a time.", EffectCategory.Player, true) },
            { "player_pacifist", new EffectInfo("Pacifist", "The player catches fire and dies if they kill anyone.", EffectCategory.Player, true, false) },
            { "player_rapid_fire", new EffectInfo("Rapid Fire", "Doubles the fire rate of the player's current weapon.", EffectCategory.Player, true) },
            { "player_rocket", new EffectInfo("Rocket Man", "Attaches an explosive to the player and launches them skyward.", EffectCategory.Player) },
            { "player_simeonsays", new EffectInfo("Simeon Says", "Displays an action command the player must follow or die.", EffectCategory.Player, true, true) },
            { "player_tp_stunt", new EffectInfo("Make Random Stunt Jump", "Teleports the player to a random stunt jump on a motorcycle.", EffectCategory.Player) },
            { "player_vr", new EffectInfo("Virtual Reality", "Simulates VR by combining a first-person view with a visible body double.", EffectCategory.Player, true, true) },
            { "player_walkonwater", new EffectInfo("Walk On Water", "Keeps the player on top of water surfaces.", EffectCategory.Player, true) },
            { "player_3stars", new EffectInfo("3 Wanted Stars", "Sets wanted level to 3 stars.", EffectCategory.Player) },
            { "player_1star", new EffectInfo("1 Wanted Star", "Sets wanted level to 1 star.", EffectCategory.Player) },
            { "player_fakestars", new EffectInfo("Fake Wanted Level", "Displays fake wanted stars that vanish after a moment.", EffectCategory.Player) },
            { "player_tired", new EffectInfo("I'm So Tired", "Forces the player to sit down and rest, disabling all controls briefly.", EffectCategory.Player, true) },
            { "player_fakedeath", new EffectInfo("Fake Death", "Plays a convincing death animation before teleporting the body away.", EffectCategory.Player) },
            { "player_zoomzoom_cam", new EffectInfo("Zoom Zoom Cam", "Oscillates the camera field of view in and out repeatedly.", EffectCategory.Player, true, true) },
            { "veh_randomseat", new EffectInfo("Set Player Into Random Vehicle Seat", "Moves the player to a random seat in their vehicle.", EffectCategory.Player) },
            { "tp_fakex2", new EffectInfo("Fake Fake Teleport", "Performs a double-fake teleport before landing at the real destination.", EffectCategory.Player) },
            { "player_tptowaypointopposite", new EffectInfo("Teleport To The Opposite Side Of Waypoint", "Teleports the player to the opposite side of their waypoint.", EffectCategory.Player) },
            { "player_tp_to_everything", new EffectInfo("Teleporter Malfunction", "Repeatedly warps the player to random nearby entities.", EffectCategory.Player, true, true) },
            
            // Peds
            { "peds_remweps", new EffectInfo("Remove Weapons From Everyone", "Removes all weapons from every ped.", EffectCategory.Peds) },
            { "spawn_grieferjesus", new EffectInfo("Spawn Griefer Jesus", "Spawns an armed Griefer Jesus who attacks the player.", EffectCategory.Peds) },
            { "peds_spawnimrage", new EffectInfo("Spawn Impotent Rage", "Spawns Impotent Rage who attacks the player.", EffectCategory.Peds) },
            { "spawn_grieferjesus2", new EffectInfo("Spawn Extreme Griefer Jesus", "Spawns an extreme Griefer Jesus on an Oppressor who attacks the player.", EffectCategory.Peds) },
            { "peds_ignite", new EffectInfo("Ignite All Nearby Peds", "Sets all nearby peds on fire.", EffectCategory.Peds) },
            { "playerveh_exit", new EffectInfo("Everyone Exits Their Vehicles", "Forces every ped out of their vehicle.", EffectCategory.Peds) },
            { "peds_riot", new EffectInfo("Peds Riot", "All peds riot, fight each other, and attack the player.", EffectCategory.Peds, true) },
            { "peds_sensitivetouch", new EffectInfo("Sensitive Touch", "Any collision causes peds to ragdoll.", EffectCategory.Peds, true, true) },
            { "peds_dance", new EffectInfo("In The Hood", "All peds freeze in place and play a looped dance animation.", EffectCategory.Peds, true) },
            { "peds_flee", new EffectInfo("All Nearby Peds Are Fleeing", "All peds panic and flee from the player.", EffectCategory.Peds) },
            { "zombies", new EffectInfo("Explosive Zombies", "Spawns a horde of hostile exploding zombies around the player.", EffectCategory.Peds, true) },
            { "peds_giverpg", new EffectInfo("Give Everyone An RPG", "Arms every ped with an RPG.", EffectCategory.Peds) },
            { "peds_stungun", new EffectInfo("Give Everyone A Stun Gun", "Arms every ped with a stun gun.", EffectCategory.Peds) },
            { "peds_minigun", new EffectInfo("Give Everyone A Minigun", "Arms every ped with a minigun.", EffectCategory.Peds) },
            { "peds_upnatomizer", new EffectInfo("Give Everyone An Up-N-Atomizer", "Arms every ped with an Up-N-Atomizer.", EffectCategory.Peds) },
            { "peds_randomwep", new EffectInfo("Give Everyone A Random Weapon", "Arms every ped with a random weapon.", EffectCategory.Peds) },
            { "peds_railgun", new EffectInfo("Give Everyone A Railgun", "Arms every ped with a railgun.", EffectCategory.Peds) },
            { "peds_battleaxe", new EffectInfo("Give Everyone A Battle Axe", "Arms every ped with a battle axe.", EffectCategory.Peds) },
            { "peds_invincible", new EffectInfo("Everyone Is Invincible", "Makes all peds completely invincible.", EffectCategory.Peds, true) },
            { "peds_blind", new EffectInfo("Blind Peds", "All peds become blind and deaf, ignoring everything around them.", EffectCategory.Peds, true) },
            { "peds_mindmg", new EffectInfo("Minimal Damage", "Reduces all damage dealt and received to minimal amounts.", EffectCategory.Peds, true) },
            { "peds_frozen", new EffectInfo("Peds Are Brainless", "Freezes all nearby peds in place.", EffectCategory.Peds, true) },
            { "peds_aimbot", new EffectInfo("Aimbot Peds", "All peds gain perfect aim and attack with relentless precision.", EffectCategory.Peds, true) },
            { "spawn_chop", new EffectInfo("Spawn Companion Doggo", "Spawns Chop the dog as a friendly companion.", EffectCategory.Peds) },
            { "spawn_chimp", new EffectInfo("Spawn Companion Chimp", "Spawns a chimp as a friendly companion.", EffectCategory.Peds) },
            { "spawn_compbrad", new EffectInfo("Spawn Companion Brad", "Spawns Brad as an armed friendly companion.", EffectCategory.Peds) },
            { "spawn_comprnd", new EffectInfo("Spawn Random Companion", "Spawns a random ped as an armed friendly companion.", EffectCategory.Peds) },
            { "playerveh_tprandompeds", new EffectInfo("Teleport Random Peds Into Current Vehicle", "Teleports random pedestrians into the player's vehicle.", EffectCategory.Peds) },
            { "peds_revive", new EffectInfo("Revive Dead Peds", "Revives dead peds as armed hostile clones.", EffectCategory.Peds) },
            { "peds_driveby", new EffectInfo("Peds Drive-By Player", "Peds in vehicles perform drive-by shootings on the player.", EffectCategory.Peds, true, true) },
            { "peds_explosive", new EffectInfo("Explosive Peds", "Peds explode with an orbital cannon blast when injured.", EffectCategory.Peds, true) },
            { "peds_portal_gun", new EffectInfo("Portal Guns", "Gunfire opens portals that teleport struck entities.", EffectCategory.Peds, true) },
            { "peds_spawnballasquad", new EffectInfo("Spawn Balla Squad", "Spawns a Balla gang squad that attacks the player.", EffectCategory.Peds) },
            { "peds_scooterbrothers", new EffectInfo("Scooter Brothers", "Puts nearby peds onto Faggio scooters.", EffectCategory.Peds) },
            { "peds_intorandomvehs", new EffectInfo("Set Everyone Into Random Vehicles", "Teleports every ped into a random available vehicle.", EffectCategory.Peds) },
            { "peds_catguns", new EffectInfo("Catto Guns", "Shots spawn ragdolling cats that fly toward the impact point.", EffectCategory.Peds, true) },
            { "peds_gunsmoke", new EffectInfo("Gunsmoke", "Smoke particles burst from peds when they fire weapons.", EffectCategory.Peds, true) },
            { "peds_mercenaries", new EffectInfo("Mercenaries", "Mercenaries arrive in helicopters and vehicles to eliminate the player.", EffectCategory.Peds, true) },
            { "peds_loosetrigger", new EffectInfo("Loose Triggers", "All peds gain infinite ammo and shoot compulsively.", EffectCategory.Peds, true) },
            { "peds_minions", new EffectInfo("Minions", "All ped voices are pitched up to ridiculous levels (minion voices).", EffectCategory.Peds, true) },
            { "peds_killerclowns", new EffectInfo("Killer Clowns", "Waves of killer clowns spawn and attack the player repeatedly.", EffectCategory.Peds, true, true) },
            { "peds_jamesbond", new EffectInfo("Spawn Deadly Agent", "A deadly armed agent spawns and hunts the player.", EffectCategory.Peds) },
            { "peds_drive_backwards", new EffectInfo("Peds Drive Backwards", "All peds in vehicles drive in reverse.", EffectCategory.Peds, true) },
            { "peds_stop_stare", new EffectInfo("Stop And Stare", "All peds stop what they are doing and stare at the player.", EffectCategory.Peds) },
            { "peds_flip", new EffectInfo("Spinning Peds", "All peds spin and rotate uncontrollably.", EffectCategory.Peds, true, true) },
            { "peds_busbois", new EffectInfo("Bus Bois", "Nearby peds are loaded into buses around the player.", EffectCategory.Peds) },
            { "peds_nailguns", new EffectInfo("Nailguns", "All peds are frozen with nailguns attached to their hands.", EffectCategory.Peds, true, true) },
            { "peds_spawn_biker", new EffectInfo("Spawn Biker", "Spawns a hostile biker on a Daemon motorcycle.", EffectCategory.Peds) },
            { "peds_spawn_juggernaut", new EffectInfo("Spawn Juggernaut", "Spawns a heavily armoured Juggernaut with a minigun.", EffectCategory.Peds) },
            { "peds_spawn_space_ranger", new EffectInfo("Spawn Space Ranger", "Spawns a Space Ranger with a ray carbine who attacks the player.", EffectCategory.Peds) },
            { "peds_mowermates", new EffectInfo("Mower Mates", "Loads nearby peds into lawnmowers around the player.", EffectCategory.Peds) },
            { "peds_tank_bois", new EffectInfo("Tanks A Lot", "Puts nearby peds into Rhino tanks.", EffectCategory.Peds) },
            { "peds_spawn_quarreling_couple", new EffectInfo("Spawn Quarreling Couple", "Spawns a quarreling couple who fight each other.", EffectCategory.Peds) },
            { "peds_bloody", new EffectInfo("Everyone Is Bloody", "Covers all peds in wound and blood decals.", EffectCategory.Peds) },
            { "peds_eternal_screams", new EffectInfo("Eternal Screams", "All peds emit continuous pain screams.", EffectCategory.Peds, true, true) },
            { "spawn_angry_chimp", new EffectInfo("Spawn Angry Chimp", "Spawns an angry armed chimp that attacks the player.", EffectCategory.Peds, true) },
            { "peds_angryalien", new EffectInfo("Spawn Angry Alien", "Spawns a high-health angry alien that attacks the player.", EffectCategory.Peds) },
            { "peds_angryjimmy", new EffectInfo("Spawn Jealous Jimmy", "Spawns Jealous Jimmy with a combat MG who attacks the player.", EffectCategory.Peds) },
            { "peds_cops", new EffectInfo("All Peds Are Cops", "All peds are converted to police officers.", EffectCategory.Peds, true) },
            { "peds_launchnearby", new EffectInfo("Launch All Nearby Peds Up", "Launches all nearby peds high into the air.", EffectCategory.Peds) },
            { "peds_attackplayer", new EffectInfo("All Peds Attack Player", "All peds become immediately hostile toward the player.", EffectCategory.Peds, true) },
            { "peds_slidy", new EffectInfo("Slidy Peds", "All peds bounce and jump uncontrollably.", EffectCategory.Peds, true) },
            { "peds_spawndancingapes", new EffectInfo("Spawn Dance Troupe", "Spawns three friendly dancing apes.", EffectCategory.Peds) },
            { "peds_phones", new EffectInfo("Whose Phone Is Ringing?", "All peds' phones ring incessantly.", EffectCategory.Peds, true) },
            { "peds_spawnrandomhostile", new EffectInfo("Spawn Random Enemy", "Spawns a random hostile enemy.", EffectCategory.Peds) },
            { "peds_spawnfancats", new EffectInfo("Spawn Fan Cats", "Spawns three friendly fan cats.", EffectCategory.Peds) },
            { "peds_obliterate", new EffectInfo("Obliterate All Nearby Peds", "Obliterates all nearby peds with orbital cannon blasts.", EffectCategory.Peds) },
            { "peds_headless", new EffectInfo("Mannequins", "Replaces all peds with invisible headless mannequins.", EffectCategory.Peds, true) },
            { "peds_2x_animation_speed", new EffectInfo("2x Animation Speed", "Doubles the animation playback speed of all peds.", EffectCategory.Peds, true) },
            { "peds_slippery_peds", new EffectInfo("Can't Tie My Shoes", "Peds ragdoll whenever they move above a certain speed.", EffectCategory.Peds, true, true) },
            { "peds_hands_up", new EffectInfo("Hands Up!", "All non-cop peds raise their hands in surrender.", EffectCategory.Peds) },
            { "peds_hotcougars", new EffectInfo("Hot Cougars In Your Area", "Aggressive cougars repeatedly spawn and attack the player.", EffectCategory.Peds, true, true) },
            { "peds_grapple_guns", new EffectInfo("Gravity Guns", "Gunfire launches struck peds backward with grapple force.", EffectCategory.Peds, true) },
            { "peds_reflectivedamage", new EffectInfo("Friendly Fire", "All damage dealt to peds is reflected back to the attacker.", EffectCategory.Peds, true, true) },
            { "peds_toast", new EffectInfo("You're Toast", "All peds have their heads replaced with bread and toasters.", EffectCategory.Peds, true) },
            { "peds_not_menendez", new EffectInfo("Not Menendez!", "Plays Menendez speech audio whenever a companion ped dies.", EffectCategory.Peds, true) },
            { "peds_roasting", new EffectInfo("Get Roasted", "Spawns Lamar who roasts the player with insults.", EffectCategory.Peds, true, true) },
            { "peds_prop_hunt", new EffectInfo("Prop Hunt", "All peds are disguised as random environment props.", EffectCategory.Peds, true) },
            { "peds_smoketrails", new EffectInfo("Smoke Trails", "All peds emit colourful smoke trails as they move.", EffectCategory.Peds, true) },
            { "peds_give_props", new EffectInfo("Give Everyone A Random Prop", "Attaches a random prop to every ped's head.", EffectCategory.Peds) },
            { "peds_ragdoll", new EffectInfo("Ragdoll Everyone", "Forces all peds into ragdoll simultaneously.", EffectCategory.Peds) },
            { "peds_ghost", new EffectInfo("Everyone Is A Ghost", "Makes all peds completely invisible.", EffectCategory.Peds, true) },
            { "peds_kifflom", new EffectInfo("Kifflom!", "All peds repeatedly shout Kifflom in religious fervour.", EffectCategory.Peds, true) },
            { "peds_sayhi", new EffectInfo("Friendly Neighborhood", "All nearby peds greet each other with friendly chatter.", EffectCategory.Peds, true) },
            { "peds_insult", new EffectInfo("Unfriendly Neighborhood", "All nearby peds insult and argue with each other.", EffectCategory.Peds, true) },
            
            // Vehicles
            { "vehs_explode", new EffectInfo("Explode All Nearby Vehicles", "Explodes all vehicles except the player's current one.", EffectCategory.Vehicle) },
            { "vehs_upupaway", new EffectInfo("Launch All Vehicles Up", "Launches all vehicles into the air.", EffectCategory.Vehicle) },
            { "playerveh_lock", new EffectInfo("Lock Player Inside Vehicle", "Locks the player inside their current vehicle.", EffectCategory.Vehicle, true) },
            { "playerveh_killengine", new EffectInfo("Kill Engine Of Every Vehicle", "Destroys the engine of every vehicle, making them undriveable.", EffectCategory.Vehicle) },
            { "vehs_red", new EffectInfo("Red Traffic", "Repaints all traffic vehicles red.", EffectCategory.Vehicle, true) },
            { "vehs_blue", new EffectInfo("Blue Traffic", "Repaints all traffic vehicles blue.", EffectCategory.Vehicle, true) },
            { "vehs_green", new EffectInfo("Green Traffic", "Repaints all traffic vehicles green.", EffectCategory.Vehicle, true) },
            { "vehs_chrome", new EffectInfo("Chrome Traffic", "Repaints all traffic vehicles chrome.", EffectCategory.Vehicle, true) },
            { "vehs_pink", new EffectInfo("Hot Traffic", "Repaints all traffic vehicles pink with fire effects.", EffectCategory.Vehicle, true) },
            { "vehs_rainbow", new EffectInfo("Rainbow Traffic", "Cycles all traffic vehicles through rainbow colours.", EffectCategory.Vehicle, true) },
            { "vehs_slippery", new EffectInfo("Slippery Vehicles", "Gives all vehicles near-zero traction.", EffectCategory.Vehicle, true) },
            { "vehs_nogravity", new EffectInfo("Vehicles Have No Gravity", "Disables gravity for all vehicles.", EffectCategory.Vehicle, true, true) },
            { "vehs_x2engine", new EffectInfo("2x Vehicle Engine Speed", "Doubles the engine power and top speed of all vehicles.", EffectCategory.Vehicle, true) },
            { "vehs_x10engine", new EffectInfo("10x Vehicle Engine Speed", "Multiplies the engine power and top speed of all vehicles by 10x.", EffectCategory.Vehicle, true) },
            { "vehs_x05engine", new EffectInfo("0.5x Vehicle Engine Speed", "Halves the engine power and top speed of all vehicles.", EffectCategory.Vehicle, true) },
            { "spawn_rhino", new EffectInfo("Spawn Rhino", "Spawns a Rhino tank for the player.", EffectCategory.Vehicle) },
            { "spawn_adder", new EffectInfo("Spawn Adder", "Spawns an Adder supercar for the player.", EffectCategory.Vehicle) },
            { "spawn_dump", new EffectInfo("Spawn Dump", "Spawns a Dump truck for the player.", EffectCategory.Vehicle) },
            { "spawn_monster", new EffectInfo("Spawn Monster", "Spawns a Monster truck for the player.", EffectCategory.Vehicle) },
            { "spawn_bmx", new EffectInfo("Spawn BMX", "Spawns a BMX bicycle for the player.", EffectCategory.Vehicle) },
            { "spawn_tug", new EffectInfo("Spawn Tug", "Spawns a Tug boat for the player.", EffectCategory.Vehicle) },
            { "spawn_cargo", new EffectInfo("Spawn Cargo Plane", "Spawns a Cargo plane for the player.", EffectCategory.Vehicle) },
            { "spawn_bus", new EffectInfo("Spawn Bus", "Spawns a Bus for the player.", EffectCategory.Vehicle) },
            { "spawn_blimp", new EffectInfo("Spawn Blimp", "Spawns a Blimp for the player.", EffectCategory.Vehicle) },
            { "spawn_buzzard", new EffectInfo("Spawn Buzzard", "Spawns a Buzzard helicopter for the player.", EffectCategory.Vehicle) },
            { "spawn_faggio", new EffectInfo("Spawn Faggio", "Spawns a Faggio scooter for the player.", EffectCategory.Vehicle) },
            { "spawn_ruiner3", new EffectInfo("Spawn Ruined Ruiner", "Spawns a heavily damaged Ruiner for the player.", EffectCategory.Vehicle) },
            { "spawn_baletrailer", new EffectInfo("Spawn Bale Trailer", "Spawns a Bale trailer for the player.", EffectCategory.Vehicle) },
            { "spawn_romero", new EffectInfo("Where's The Funeral?", "Spawns a Romero hearse for the player.", EffectCategory.Vehicle) },
            { "spawn_random", new EffectInfo("Spawn Random Vehicle", "Spawns a fully upgraded random vehicle for the player.", EffectCategory.Vehicle) },
            { "notraffic", new EffectInfo("No Traffic", "Prevents any traffic vehicles from spawning.", EffectCategory.Vehicle, true) },
            { "playerveh_explode", new EffectInfo("Detonate Current Vehicle", "Starts a 5-second countdown before detonating the player's vehicle.", EffectCategory.Vehicle) },
            { "vehs_ghost", new EffectInfo("Invisible Vehicles", "Makes all vehicles invisible while keeping their collision.", EffectCategory.Vehicle, true) },
            { "vehs_honkboost", new EffectInfo("Honk Boosting", "Applies a forward thrust to the player's vehicle while honking.", EffectCategory.Vehicle, true) },
            { "playerveh_repair", new EffectInfo("Repair All Vehicles", "Fully repairs every vehicle on the map.", EffectCategory.Vehicle) },
            { "playerveh_poptires", new EffectInfo("Pop Tires Of Every Vehicle", "Pops all tyres on every vehicle.", EffectCategory.Vehicle) },
            { "vehs_poptiresconstant", new EffectInfo("Now This Is Some Tire Poppin'", "Continuously pops all tyres on every vehicle.", EffectCategory.Vehicle, true, true) },
            { "playerveh_breakdoors", new EffectInfo("Break Doors Of Every Vehicle", "Breaks all doors off every vehicle.", EffectCategory.Vehicle) },
            { "vehs_jumpy", new EffectInfo("Jumpy Vehicles", "Periodically launches nearby vehicles into the air.", EffectCategory.Vehicle, true, true) },
            { "vehs_lockdoors", new EffectInfo("Lock All Vehicles", "Locks the doors of every vehicle.", EffectCategory.Vehicle) },
            { "vehs_honkconstant", new EffectInfo("All Vehicles Honk", "Makes every vehicle honk its horn continuously.", EffectCategory.Vehicle, true) },
            { "playerveh_maxupgrades", new EffectInfo("Add Max Upgrades To Every Vehicle", "Applies maximum performance upgrades and cosmetics to all vehicles.", EffectCategory.Vehicle) },
            { "playerveh_randupgrades", new EffectInfo("Add Random Upgrades To Every Vehicle", "Applies random upgrades and cosmetics to all vehicles.", EffectCategory.Vehicle) },
            { "spawn_bluesultan", new EffectInfo("Spawn Blue Sultan", "Spawns an armed blue Sultan that attacks the player.", EffectCategory.Peds) },
            { "traffic_gtao", new EffectInfo("Traffic Magnet", "Makes all traffic AI target and ram the player.", EffectCategory.Vehicle, true) },
            { "traffic_fullaccel", new EffectInfo("Full Acceleration", "Makes all traffic accelerate to double their top speed.", EffectCategory.Vehicle, true, true) },
            { "vehs_invincible", new EffectInfo("All Vehicles Are Invulnerable", "Makes all vehicles completely indestructible.", EffectCategory.Vehicle, true) },
            { "playerveh_despawn", new EffectInfo("Remove Current Vehicle", "Removes the player's current vehicle and ragdolls its passengers.", EffectCategory.Vehicle) },
            { "vehs_alarmloop", new EffectInfo("Alarmy Vehicles", "Triggers all vehicle alarms every 2 seconds.", EffectCategory.Vehicle, true) },
            { "veh_30mphlimit", new EffectInfo("30MPH Speed Limit", "Caps all vehicles at 30 mph.", EffectCategory.Vehicle, true, true) },
            { "veh_jesustakethewheel", new EffectInfo("Jesus Take The Wheel", "Summons an AI driver to take over and drive the player's vehicle.", EffectCategory.Vehicle) },
            { "veh_poptire", new EffectInfo("Random Tire Popping", "Randomly pops or repairs a tyre on every vehicle every few seconds.", EffectCategory.Vehicle, true, true) },
            { "vehs_ohko", new EffectInfo("Vehicles Explode On Impact", "Vehicles explode on any collision.", EffectCategory.Vehicle, true) },
            { "vehs_spamdoors", new EffectInfo("Spammy Vehicle Doors", "Continuously opens and closes all vehicle doors.", EffectCategory.Vehicle, true) },
            { "veh_speed_goal", new EffectInfo("Need For Speed", "Blows up the player's vehicle if they slow below 50% top speed for too long.", EffectCategory.Vehicle, true, true) },
            { "vehs_flyingcars", new EffectInfo("Flying Cars", "Grants all vehicles 6-axis flight controls.", EffectCategory.Vehicle, true) },
            { "vehs_beyblade", new EffectInfo("Beyblades", "Spins all unoccupied vehicles wildly in place.", EffectCategory.Vehicle, true, true) },
            { "vehs_rotall", new EffectInfo("Flip All Vehicles", "Randomly flips every vehicle onto its roof or side.", EffectCategory.Vehicle) },
            { "misc_replacevehicle", new EffectInfo("Replace Current Vehicle", "Replaces the player's current vehicle with a random one.", EffectCategory.Vehicle) },
            { "veh_repossession", new EffectInfo("Repossession", "Spawns Franklin to repossess and drive away the player's vehicle.", EffectCategory.Vehicle) },
            { "vehs_spawn_wizard_broom", new EffectInfo("You're A Wizard, Franklin", "Spawns an invisible Oppressor with a broom for the player to ride.", EffectCategory.Vehicle) },
            { "veh_bouncy", new EffectInfo("Bouncy Vehicles", "Makes vehicles bounce away from anything they collide with.", EffectCategory.Vehicle, true, false) },
            { "veh_randtraffic", new EffectInfo("Random Traffic", "Continuously replaces all traffic with random vehicle models.", EffectCategory.Vehicle, true) },
            { "veh_brakeboost", new EffectInfo("Brake Boosting", "Applies a forward thrust when braking.", EffectCategory.Vehicle, true) },
            { "veh_boostbrake", new EffectInfo("Boost Braking", "Applies a reverse braking thrust to the vehicle.", EffectCategory.Vehicle, true) },
            { "vehs_crumble", new EffectInfo("Crumbling Vehicles", "Randomly damages vehicle components over time.", EffectCategory.Vehicle, true, true) },
            { "vehs_cruise_control", new EffectInfo("Cruise Control", "Maintains a constant vehicle speed once it is reached.", EffectCategory.Vehicle, true, true) },
            { "vehs_detach_wheel", new EffectInfo("Detach Random Wheel", "Detaches a random wheel from the player's vehicle.", EffectCategory.Vehicle) },
            { "vehs_disassemble", new EffectInfo("Disassemble Current Vehicle", "Removes all detachable parts from the player's vehicle.", EffectCategory.Vehicle) },
            { "vehs_prop_models", new EffectInfo("Prop Cars", "Replaces all vehicle models with random environment props.", EffectCategory.Vehicle, true) },
            { "vehs_tiny", new EffectInfo("Tiny Vehicles", "Shrinks all vehicles to half their normal size.", EffectCategory.Vehicle, true) },
            { "veh_weapons", new EffectInfo("Vehicles Shoot Rockets", "Allows the player to fire rockets from their vehicle by holding the attack button.", EffectCategory.Vehicle, true) },
        };
    }
}
