/*
	Effect by yzimroni
*/

#include <stdafx.h>

static void OnTick()
{
	// Disable all weapon change/select actions
	DISABLE_CONTROL_ACTION(0, 12, true);
	DISABLE_CONTROL_ACTION(0, 13, true);
	DISABLE_CONTROL_ACTION(0, 14, true);
	DISABLE_CONTROL_ACTION(0, 15, true);
	DISABLE_CONTROL_ACTION(0, 16, true);
	DISABLE_CONTROL_ACTION(0, 17, true);
	DISABLE_CONTROL_ACTION(0, 37, true);
	DISABLE_CONTROL_ACTION(0, 56, true);
	DISABLE_CONTROL_ACTION(0, 99, true);
	DISABLE_CONTROL_ACTION(0, 100, true);
	DISABLE_CONTROL_ACTION(0, 115, true);
	DISABLE_CONTROL_ACTION(0, 116, true);
	DISABLE_CONTROL_ACTION(0, 157, true);
	DISABLE_CONTROL_ACTION(0, 158, true);
	DISABLE_CONTROL_ACTION(0, 159, true);
	DISABLE_CONTROL_ACTION(0, 160, true);
	DISABLE_CONTROL_ACTION(0, 161, true);
	DISABLE_CONTROL_ACTION(0, 162, true);
	DISABLE_CONTROL_ACTION(0, 163, true);
	DISABLE_CONTROL_ACTION(0, 164, true);
	DISABLE_CONTROL_ACTION(0, 165, true);
	DISABLE_CONTROL_ACTION(0, 261, true);
	DISABLE_CONTROL_ACTION(0, 262, true);
}

static RegisterEffect registerEffect(EFFECT_PLAYER_WEAPON_LOCK, nullptr, nullptr, OnTick);
