/*
	Effect by Lucas7yoshi
*/

#include <stdafx.h>

static int sf = 0;

static void OnTick()
{
	HIDE_HUD_AND_RADAR_THIS_FRAME();
	DRAW_SCALEFORM_MOVIE_FULLSCREEN(sf, 100, 100, 100, 255, 0);
}

static void OnStart()
{
	sf = _REQUEST_SCALEFORM_MOVIE_2("HACKING_MESSAGE");
	while (!HAS_SCALEFORM_MOVIE_LOADED(sf))
	{
		WAIT(0);
	}
	BEGIN_SCALEFORM_MOVIE_METHOD(sf, "SET_DISPLAY");
	SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(5);
	SCALEFORM_MOVIE_METHOD_ADD_PARAM_PLAYER_NAME_STRING("C H A O S   M O D");
	SCALEFORM_MOVIE_METHOD_ADD_PARAM_PLAYER_NAME_STRING("");
	SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(45);
	SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(203);
	SCALEFORM_MOVIE_METHOD_ADD_PARAM_INT(134);
	SCALEFORM_MOVIE_METHOD_ADD_PARAM_BOOL(false);
	END_SCALEFORM_MOVIE_METHOD();
}

static RegisterEffect registerEffect(EFFECT_MISC_LESTER, OnStart, nullptr, OnTick, EffectInfo
	{
		.Name = "Pwned",
		.Id = "misc_lester",
		.IsTimed = true,
		.IsShortDuration = true,
		.IncompatibleWith = { EFFECT_VEH_SPEED_MINIMUM }
	}
);