#pragma once

#define OPTION_DEFAULT_EFFECT_SPAWN_TIME 30
#define OPTION_DEFAULT_EFFECT_TIMED_DUR 90
#define OPTION_DEFAULT_EFFECT_SHORT_TIMED_DUR 30

#define OPTION_DEFAULT_EFFECT_META_SPAWN_TIME 600
#define OPTION_DEFAULT_EFFECT_META_TIMED_DUR 95
#define OPTION_DEFAULT_EFFECT_META_SHORT_TIMED_DUR 65

#define OPTION_DEFAULT_TWITCH_VOTING_ENABLED false
#define OPTION_DEFAULT_TWITCH_OVERLAY_MODE 0

#define OPTION_DEFAULT_TWITCH_SECS_BEFORE_VOTING 0

#define OPTION_DEFAULT_TWITCH_PROPORTIONAL_VOTING false
#define OPTION_DEFAULT_TWITCH_PROPORTIONAL_VOTING_RETAIN_CHANCE true

#define OPTION_DEFAULT_TWITCH_RANDOM_EFFECT true

#define OPTION_DEFAULT_SHORTCUT_CLEAR_EFFECTS true
#define OPTION_DEFAULT_SHORTCUT_TOGGLE_MOD true
#define OPTION_DEFAULT_SHORTCUT_PAUSE_TIMER false

#define OPTION_DEFAULT_DEBUG_MENU false

#define OPTION_DEFAULT_NO_EFFECT_BAR false
#define OPTION_DEFAULT_NO_TEXT_DRAW false

#define OPTION_DEFAULT_BAR_COLOR "#FF4040FF"
#define OPTION_DEFAULT_TEXT_COLOR "#FFFFFFFF"
#define OPTION_DEFAULT_TIMED_COLOR "#FFB4B4B4"

#define OPTION_DEFAULT_DISABLE_STARTUP false
#define OPTION_DEFAULT_GROUP_WEIGHTING true
#define OPTION_DEFAULT_FAILSAFE true